[project]
name = "realtimeclickstream"
version = "0.1.0"
description = "Learn Lambda Architecture and AWS streaming services with a real-time clickstream pipeline"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.91",
    "pandas>=3.0.2",
    "pyspark>=4.1.1",
    "python-dotenv>=1.2.2",
    "tqdm>=4.67.3",
]
